name: fsync

on:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours

jobs:
  gh_fsync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: gleich/gh_fsync@master
