name: lint

on:
  - push
  - pull_request

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run Golangci Linter
        uses: golangci/golangci-lint-action@v2.3.0
  gomod:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go
      - name: Checkout Repository
        uses: actions/checkout@v2
      - run: make lint-gomod
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run Check
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: check
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Linting Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: 'Dockerfile'
      - name: Linting dev.Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: 'dev.Dockerfile'
      - name: Linting dev.lint.Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: 'dev.lint.Dockerfile'
  in-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make docker-lint
